# Generated by Django 5.0.3 on 2024-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='milage',
            field=models.IntegerField(default=50),
        ),
    ]
