# Generated by Django 5.0.3 on 2024-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipe_name', models.CharField(max_length=100)),
                ('Receipe_description', models.TextField()),
                ('Receipe_image', models.ImageField(upload_to='Receipe')),
            ],
        ),
    ]
